### ISSUE TITLE
a clear identification of the outcome variable

### ISSUE THREAD

**Issue by FeardaMeow** [sarenehan/stat-504-airbnb#5]

**Comment by sarenehan** [comment]
The outcome variable is the list price per night of Airbnb listings in Amsterdam. It should be noted that list price per night does not necessarily denote value, as overpriced units may not be rented out. Thus, analysis of the power of the selected variables to predict list price will not be extended to represent the power to predict value of the units. Nevertheless, Airbnb hosts are likely to charge what their places are worth so the analysis of the variables' ability to predict list price per night remains interesting and relevant.
